// <auto-generated />
using System;
using HW_4_6_Module;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HW_4_6_Module.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230222123550_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HW_4_6_Module.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Artist");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1967, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfDeath = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email1@gmail.com",
                            InstagramUrl = "instagram.com/artist1",
                            Name = "Artist1",
                            Phone = "+380849519323"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1999, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email2@gmail.com",
                            InstagramUrl = "instagram.com/artist2",
                            Name = "Artist2",
                            Phone = "+38090329002"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1944, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfDeath = new DateTime(2021, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email3@gmail.com",
                            InstagramUrl = "instagram.com/artist3",
                            Name = "Artist3",
                            Phone = "+38084900003"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1983, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email4@gmail.com",
                            InstagramUrl = "instagram.com/artist4",
                            Name = "Artist4",
                            Phone = "+38084950004"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1972, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfDeath = new DateTime(2021, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email5@gmail.com",
                            InstagramUrl = "instagram.com/artist5",
                            Name = "Artist5",
                            Phone = "+380819510005"
                        });
                });

            modelBuilder.Entity("HW_4_6_Module.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Pop"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Rock"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Jazz"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Hip-Hop"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Metal"
                        });
                });

            modelBuilder.Entity("HW_4_6_Module.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Duration")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleasedDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Song");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 3.22m,
                            GenreId = 1,
                            ReleasedDate = new DateTime(2022, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song1"
                        },
                        new
                        {
                            Id = 2,
                            Duration = 2.53m,
                            GenreId = 2,
                            ReleasedDate = new DateTime(2002, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song2"
                        },
                        new
                        {
                            Id = 3,
                            Duration = 2.02m,
                            GenreId = 3,
                            ReleasedDate = new DateTime(1959, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song3"
                        },
                        new
                        {
                            Id = 4,
                            Duration = 3.22m,
                            ReleasedDate = new DateTime(1872, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song4"
                        },
                        new
                        {
                            Id = 5,
                            Duration = 4.11m,
                            GenreId = 5,
                            ReleasedDate = new DateTime(2010, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song5"
                        });
                });

            modelBuilder.Entity("HW_4_6_Module.Models.SongArtist", b =>
                {
                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.HasKey("SongId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("SongArtists");

                    b.HasData(
                        new
                        {
                            SongId = 1,
                            ArtistId = 1
                        },
                        new
                        {
                            SongId = 2,
                            ArtistId = 2
                        },
                        new
                        {
                            SongId = 1,
                            ArtistId = 3
                        },
                        new
                        {
                            SongId = 2,
                            ArtistId = 4
                        },
                        new
                        {
                            SongId = 3,
                            ArtistId = 5
                        },
                        new
                        {
                            SongId = 4,
                            ArtistId = 1
                        });
                });

            modelBuilder.Entity("HW_4_6_Module.Models.Song", b =>
                {
                    b.HasOne("HW_4_6_Module.Models.Genre", "Genre")
                        .WithMany("Song")
                        .HasForeignKey("GenreId");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("HW_4_6_Module.Models.SongArtist", b =>
                {
                    b.HasOne("HW_4_6_Module.Models.Artist", "Artist")
                        .WithMany("Song")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HW_4_6_Module.Models.Song", "Song")
                        .WithMany("Artist")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("HW_4_6_Module.Models.Artist", b =>
                {
                    b.Navigation("Song");
                });

            modelBuilder.Entity("HW_4_6_Module.Models.Genre", b =>
                {
                    b.Navigation("Song");
                });

            modelBuilder.Entity("HW_4_6_Module.Models.Song", b =>
                {
                    b.Navigation("Artist");
                });
#pragma warning restore 612, 618
        }
    }
}
